#define ELSE              101
#define IF                102
#define RETURN            103
#define WHILE             104
#define PROGRAM           105
#define DECLARE           106
#define DOUBLEWHILE       107
#define LOOP              108
#define EXIT              109
#define FORCASE           110
#define INCASE            111
#define WHEN              112       
#define DEFAULT           113
#define NOT               114    
#define AND               115   
#define OR                116
#define FUNCTION          117
#define PROCEDURE         118
#define CALL              119
#define IN                120
#define INOUT             121
#define INPUT             122
#define PRINT             123
#define DEC_CONST         124
#define IDENTIFIER        125
#define PLUS              126
#define MINUS             127
#define STAR              128
#define DIV               139
#define L_THAN            130
#define G_THAN            131
#define EQUAL             132
#define L_EQ_THAN         133
#define G_EQ_THAN         134
#define NEQUAL            135
#define ASSIGN            136
#define LPAREN            137
#define RPAREN            138
#define SEMICOLON         149
#define COMMA             140
#define COLON             141
#define LSQUARE_BRACK     142
#define RSQUARE_BRACK     143
#define LBRACK            144
#define RBRACK            145
#define REM               146
#define STRING_LITERAL    147
#define ENDL              148